### ISSUE TITLE
[VASL] NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#2010]
transferred from vassalengine/modules#2860

**Comment by geezer09** [comment]
This is using VASL 6.6.6 Do we even want to look into it? Why are people using such outdated versions? I think bug reports that are not from the current or the previous version should probably be ignored. 

It can be quite a waste of time trying to track down a bug that was already fixed ...

**Comment by zgrose** [comment]
It is very much not fixed. 

<img width="359" alt="Image" src="https://github.com/user-attachments/assets/0d481b9e-3a69-4bed-97b5-3255ef7626f5" />

**Comment by geezer09** [comment]
I can see that the error is not being handled properly, but ... from the log

2025-02-10 10:34:16,433 [16108-Thread-0] INFO  VASSAL.build.module.GameState - This save was created with the module named 'VSQL', but you are running module 'VASL'
2025-02-10 10:34:18,994 [16108-Thread-0] INFO  VASSAL.build.module.GameState - This save was created with Module version '4.1.96' but you are running '6.6.6'
2025-02-10 10:34:18,994 [16108-Thread-0] INFO  VASSAL.build.module.GameState - This save was created with Vassal version '3.1' but you are running '3.7'


If the error is not being handled properly but is also never occuring, i don't really care enough to try and fix it. The fact that it occured with these archaic versions (what is VSQL anyways, is that base Squad leader?) does not trouble me at all.

**Comment by zgrose** [comment]
No skin off my back if this doesn't get fixed, I just hope everyone has moved on from ever writing code like this in 2025 and beyond. :)

**Comment by derimmer** [comment]
As far as I can see, the user was trying to resurrect a game saved in a very old version. We do make provision for that. So worth fixing in my view. 

Plus, I am trying to learn how to handle bugs that cause VASL to crash. So, any NPE or the like. 

Here is the fix that I am proposing. Does it look like the right/best way to handle this error, trivial as it may be? Your advice much appreciated. Line 211 is now where the crash will occur. I am wrapping it in a try-catch and handling the exception by setting the currentTurn to a default value. I could go with 0 rather than 1?

<img width="572" height="488" alt="Image" src="https://github.com/user-attachments/assets/c4bf53e3-e359-42b1-baaa-bc70e4a4ae9e" />

**Comment by zgrose** [comment]
Unless those other setters are going to throw NumberFormatExceptions you probably want to keep the catch closer to the try.
````
try {
  Integer currentTurn = Integer.parseInt(c);
  turn.current = currentTurn;
} catch (NumberFormatException e) {
  turn.current = 1;
}
````

The way you have it now, if the parse throws an exception, the current turn will be set, but the SANs, BoobyTrap, ELR, etc would not be set.

**Comment by derimmer** [comment]
@zgrose you are correct of course and I have changed the fix and pushed it (using the wrong issue number, wtf@!).
